config/routes.rb
Rails.application.routes.draw do
  root 'store#home', as: 'home'

  resources :orders, only: [:show, :index]

  resources :carts, only: [:show]
  post 'carts/checkout' => 'carts#checkout', as: :checkout

  resources :categories, only: [:index]

  resources :items, only: [:index, :show, :new, :create, :edit, :update]

  resources :items, only: [:show] do
    resources :reviews, only: [:index, :create, :new]
  end

  resources :reviews, only: [:show]

  resources :line_items, only: [:create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :categories, only: [:show] do
    resources :items, only: [:index, :show] 
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items
	has_many :items, through: :line_items
	belongs_to :user
	belongs_to :order

	def total
		self.line_items.collect{|line_item| line_item.item.price*line_item.quantity}.sum
	end

	def add_item(item_id)
		item = Item.find(item_id)
		if self.items.include?(item)
			line_item = self.line_items.find_by(item_id: item_id)
			line_item.quantity += 1
			line_item.save
		else
			line_item = self.line_items.build(item_id: item_id)
		end
		line_item
	end

	def checkout
		self.line_items.each do |line_item|
			line_item.item.inventory -= line_item.quantity
			line_item.item.save
		end
	end

	def new_order
		order = self.build_order(order_time: Time.now)
		self.save
		order
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	has_many :carts, through: :line_items
	belongs_to :category
	has_many :reviews

	accepts_nested_attributes_for :category

	has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :inventory, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	def self.new_products
		self.all.last(4)
	end

	def self.featured_products
		self.all.sample(8)
	end

	def in_stock?
		self.inventory > 0
	end
			
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :item
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_one :cart
	has_many :line_items, through: :cart
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :item
	validates :star, presence: true
	validates :title, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :omniauth_providers => [:facebook]
         # :recoverable, :rememberable, :trackable, :validatable

  has_many :carts
  has_many :orders
	belongs_to :current_cart, class_name: "Cart"

	enum role: [:normal, :admin]

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
 

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	private

	def user_not_authorized
	  flash[:warning] = "You are not authorized to perform this action."
	  redirect_to(request.referrer || home_path)
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@cart = Cart.find(params[:id])
  	authorize @cart
  end

  def checkout
  	cart = Cart.find(params[:id])
  	cart.checkout
  	order = cart.new_order
  	order.user = current_user
  	order.save
		current_user.current_cart = nil
		current_user.save
		redirect_to order_path(order)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

end

app/controllers/category_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		if params[:category_id]
			@category = Category.find(params[:category_id])
      @items = @category.items
    else
      @items = Item.all
    end
	end

	def new
		@item = Item.new
		authorize @item
	end

	def create
		@item = Item.create(item_params)
		if @item.valid?
			redirect_to item_path(@item)
		else
			render "items/new"
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
		authorize @item
	end

	def update
		@item = Item.find(params[:id])
		if @item.valid?
			@item.update(item_params)
			redirect_to item_path(@item)
		else
			render "items/edit"
		end
	end

	def destroy
		@item = Item.find(params[:id])
		authorize @item
		@item.delete
		redirect_to items_path
	end

	private

	def item_params
		params.require(:item).permit(:image, :name, :description, :image_url, :price, :inventory, :category_id, categories_attributes: [:name])
	end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	def create
		line_item = LineItem.find_or_create_by(item_id: params[:item_id])
		if current_cart = current_user.current_cart
			current_cart.add_item(params[:item_id])
			current_cart.save
		else
			current_cart = current_user.carts.create
			current_cart.add_item(params[:item_id])
			current_cart.save
			current_user.current_cart = current_cart
			current_user.save
		end
		redirect_to cart_path(current_cart)
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to home_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
  	@order = Order.find(params[:id])
  	authorize @order
  end

  def index
  	@orders = Order.all
  	authorize @orders
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_item

	def index
		@reviews = @item.reviews
		render 'index.js'
	end

	def new
		@review = Review.new
		render 'new.js', layout: false
	end

	def create
		@review = @item.reviews.create(review_params)
		render json:@review
	end

	private

		def set_item
			@item = Item.find(params[:item_id])
		end

		def review_params
			params.require(:review).permit(:star, :title, :content)
		end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def home
  	@categories = Category.all
  	@items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/show.html.erb
<h1>Your Cart</h1>
<ul>
	<% @cart.line_items.each do |line_item| %>
		<li><%= line_item.item.name %>: <%= line_item.quantity %></li>
	<% end %>
</ul>
<hr>
<p><strong>Your Total: <%= number_to_currency(@cart.total) %></strong></p>
<br>
<%= button_to "Checkout", checkout_path(id: @cart.id) %>

app/views/categories/index.html.erb
<h1>All Categories</h1>
<ul>
	<% @categories.each do |category| %>
		<li><%= link_to "#{category.name}", category_items_path(category.id) %></li>
	<% end %>
</ul>

app/views/items/_detail.html.erb
<div id="detail-div">
	<p><%= @item.description %></p>
	<% if @item.in_stock? %>
		<h4><%= @item.inventory %> left</h4>
	<% else %>
		<h4>Out of Stock</h4>
	<% end %>
	<h4><%= number_to_currency(@item.price) %></h4>
	<br>
	<% if @item.in_stock? %>
		<%= button_to 'Add to Cart', line_items_path(item_id: @item.id), class: "btn btn-primary" unless current_user.nil? %>
	<% end %>
</div>

app/views/items/_errors.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
 
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
	<div class="form-group">
	<%= f.label :image %>
  <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">	
	<%= f.label :name %>
	<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
	<%= f.label :description %>
	<%= f.text_area :description, class: "form-control"  %>
	</div>
	<div class="form-group">
	<%= f.label :price %>
	<%= f.text_field :price, class: "form-control"  %>
	</div>
	<div class="form-group">
	<%= f.label :inventory %>
	<%= f.text_field :inventory, class: "form-control"  %>
	</div>
	<div class="form-group">
	<%= f.label :category_id %>
	<%= f.collection_select :category_id, Category.all, :id, :name %>
	</div>
	<%= f.submit %>
<% end %>

app/views/items/_item_block.html.erb
<div class="item-block col-sm-2">
	<%= link_to image_tag(item.image.url, class: "item-block-img"), category_item_path(item.category.id, item.id) %>
	<br>
	<div class="overlay">
		<div class="item-link">
			<%= link_to "#{item.name}", category_item_path(item.category.id, item.id)%>
		</div>
	</div>
</div>

app/views/items/edit.html.erb
<h1>Edit Item</h1>
<%= render 'errors' %>
<div>
	<%= button_to "Delete Item", item_path(@item), method: :delete %>
</div>
<br>
<%= render 'form' %>

app/views/items/index.html.erb
<% if @category %>
	<div class="category-headline">
		<h1><%= @category.name %></h1>
	</div>
<% end %>

<div class="row">
<% @items.each do |item| %>
	<%= render partial: "items/item_block", locals: {item: item} %>
<% end %>
</div>

app/views/items/new.html.erb
<h1>Create New Item</h1>
<%= render 'errors' %>
<%= render 'form' %>

app/views/items/show.html.erb
<div>
	<p>Back to <%= link_to "#{@item.category.name}", category_items_path(@item.category.id) %>
</div>

<div class="row">
	<div class="col-md-1">
	</div>

	<div class="col-md-11 item-headline">
		<h1><%= @item.name %></h1>
		<br>
		<% if current_user.try(:admin?) %>
			<%= link_to "Edit Item", edit_item_path(@item) %>
		<% end %>
	</div>
</div>

<div class="row">
	<div class="col-md-1">
	</div>

	<div class="col-md-4">
		<%= image_tag @item.image.url, class: "img-responsive" %>
	</div>

	<div class="col-md-6 right">
		<ul class="nav nav-tabs nav-justified">
			<li><a href="" data-itemId="<%= @item.id %>" id="item-detail-button">Detail</a></li>
			<li><a href="" data-itemId="<%= @item.id %>" id="item-reviews-button">Reviews</a></li>
		</ul>
		<div id="item-info">
			<%= render 'detail' %>
		</div>
	</div>

	<div class="col-md-1">
	</div>

</div>

<script id="review-template" type="text/x-handlebars-template">
	<div class="review-div">
		{{#times star}}
			<i class="fa fa-star" aria-hidden="true"></i>
		{{/times}}
		<h3>{{title}}</h3>
		<p>{{content}}</p>
		<hr>
	</div>
</script>

app/views/items/show.js.erb
var html = "<%= j render 'detail' %>"
$("#item-info").html(html)

app/views/orders/index.html.erb
<ul>
	<% @orders.each do |order| %>
		<li><%= link_to "Order ##{order.id}", order_path(order) unless order.processed %></li>
	<% end %>
</ul>

app/views/orders/show.html.erb
<h1>Order #<%= @order.id %></h1>
<h5>Time ordered: <%= @order.order_time %></h5>
<ul>
	<% @order.line_items.each do |line_item| %>
		<li><%= link_to "#{line_item.item.name}", item_path(line_item.item) %> | Quantity: <%= line_item.quantity %></li>
	<% end %>
</ul>
<hr>
<p><strong>Total: <%= number_to_currency(@order.cart.total) %></strong></p>