config/routes.rb
Rails.application.routes.draw do
  root 'store#home', as: 'home'

  resources :orders, only: [:show, :index]

  resources :carts, only: [:show]
  post 'carts/checkout' => 'carts#checkout', as: :checkout

  resources :categories, only: [:index]

  resources :items, only: [:index, :show, :new, :create, :edit, :update]

  resources :items, only: [:show] do
    resources :reviews, only: [:index, :create, :new]
  end

  resources :reviews, only: [:show]

  resources :line_items, only: [:create]

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :categories, only: [:show] do
    resources :items, only: [:index, :show] 
  end

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items
	has_many :items, through: :line_items
	belongs_to :user
	belongs_to :order

	def total
		self.line_items.collect{|line_item| line_item.item.price*line_item.quantity}.sum
	end

	def add_item(item_id)
		item = Item.find(item_id)
		if self.items.include?(item)
			line_item = self.line_items.find_by(item_id: item_id)
			line_item.quantity += 1
			line_item.save
		else
			line_item = self.line_items.build(item_id: item_id)
		end
		line_item
	end

	def checkout
		self.line_items.each do |line_item|
			line_item.item.inventory -= line_item.quantity
			line_item.item.save
		end
	end

	def new_order
		order = self.build_order(order_time: Time.now)
		self.save
		order
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :line_items
	has_many :carts, through: :line_items
	belongs_to :category
	has_many :reviews

	accepts_nested_attributes_for :category

	has_attached_file :image
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :price, presence: true, numericality: { greater_than: 0 }
	validates :inventory, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

	def self.new_products
		self.all.last(4)
	end

	def self.featured_products
		self.all.sample(8)
	end

	def in_stock?
		self.inventory > 0
	end
			
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :cart
	belongs_to :item
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_one :cart
	has_many :line_items, through: :cart
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :item
	validates :star, presence: true
	validates :title, presence: true
	validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :omniauth_providers => [:facebook]
         # :recoverable, :rememberable, :trackable, :validatable

  has_many :carts
  has_many :orders
	belongs_to :current_cart, class_name: "Cart"

	enum role: [:normal, :admin]

	def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

	
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@cart = Cart.find(params[:id])
  	authorize @cart
  end

  def checkout
  	cart = Cart.find(params[:id])
  	cart.checkout
  	order = cart.new_order
  	order.user = current_user
  	order.save
		current_user.current_cart = nil
		current_user.save
		redirect_to order_path(order)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

end

app/controllers/category_controller.rb
class CategoriesController < ApplicationController
  def index
  	@categories = Category.all
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		if params[:category_id]
			@category = Category.find(params[:category_id])
      @items = @category.items
    else
      @items = Item.all
    end
	end

	def new
		@item = Item.new
		authorize @item
	end

	def create
		@item = Item.create(item_params)
		if @item.valid?
			redirect_to item_path(@item)
		else
			render "items/new"
		end
	end

	def show
		@item = Item.find(params[:id])
	end

	def edit
		@item = Item.find(params[:id])
		authorize @item
	end

	def update
		@item = Item.find(params[:id])
		if @item.valid?
			@item.update(item_params)
			redirect_to item_path(@item)
		else
			render "items/edit"
		end
	end

	def destroy
		@item = Item.find(params[:id])
		authorize @item
		@item.delete
		redirect_to items_path
	end

	private

	def item_params
		params.require(:item).permit(:image, :name, :description, :image_url, :price, :inventory, :category_id, categories_attributes: [:name])
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
  	@order = Order.find(params[:id])
  	authorize @order
  end

  def index
  	@orders = Order.all
  	authorize @orders
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_item

	def index
		@reviews = @item.reviews
		render 'index.js'
	end

	def new
		@review = Review.new
		render 'new.js', layout: false
	end

	def create
		@review = @item.reviews.create(review_params)
		render json:@review
	end

	private

		def set_item
			@item = Item.find(params[:item_id])
		end

		def review_params
			params.require(:review).permit(:star, :title, :content)
		end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def home
  	@categories = Category.all
  	@items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
		<%= content_tag :div, msg, :class => "flash_#{name}" %>
	<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">HomeDec</a>
    </div>

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Categories<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_items_path(category.id) %></li>
          <% end %>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
      <% if current_user.admin? %>
        <li><%= link_to "Create New Item", new_item_path %></li>
        <li><%= link_to "View Orders", orders_path %></li>
      <% end %>
      <% if current_user.current_cart %>
        <li> <%= link_to "Cart", cart_path(current_user.current_cart) %></li>
      <% end %>
      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "sign in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <%end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineStore</title>
  <!-- fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">

  <script src="https://use.fontawesome.com/f681164266.js"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container">
		<%= render 'layouts/message' %>
		<%= yield %>
	</div>
</body>
</html>